### PR TITLE
OGM-1357 Fix build on Travis

### PR DESCRIPTION
**Pull request by DavideD**
Follows: https://github.com/hibernate/hibernate-ogm/pull/934

https://hibernate.atlassian.net/browse/OGM-1357

I've created a new branch and re-run the build and it seems that everything works now:
https://travis-ci.org/DavideD/hibernate-ogm/builds/328078838

### CODE REVIEW

**Comment by yrodiere** [comment]
I honestly don't understand how these changes could fix the problem... Maybe you can explain a bit?
Anyway, I started a dozen builds on Travis, let's see how it goes.

**Comment by DavideD** [comment]
I wonder if it's reusing the server folder somehow

**Comment by DavideD** [comment]
It still doesn't work

**Comment by yrodiere** [comment]
Can confirm: out of 5 finished builds so far, only one succeeded.

**Comment by DavideD** [comment]
Ok, I see if I can find the real cause

**Pull request closed without merging**
