### PR TITLE
OGM-1397 Counter name should contain the table for @TableGenerator

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-1397

Is it OK to include it for the next release?
If they update the library, people might have problem since the name of the counters has changed

### CODE REVIEW

**Comment by fax4ever** [comment]
I reviewed it: in my opinion it is ok.
If we want insert in the next release I can merge it.

**Comment by DavideD** [comment]
@Sanne is it OK to include this for 5.3 CR1 ?

**Comment by Sanne** [comment]
yes better have it now than after a Final, since it changes the schema.

**Comment by DavideD** [comment]
Cool, thanks

**Pull request merged**
