### PR TITLE
OGM-917 one more test case with EmbeddedId and mongodb

### PR DESCRIPTION
**Pull request by shuraa**
PR contains only test case, no fix for the issue.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Ok to test.

**Comment by gunnarmorling** [comment]
Thanks, @shuraa! Do you have any idea about the actual cause of this?

**Comment by shuraa** [comment]
@gunnarmorling have no idea yet. I'll try to investigate the issue on this week.

**Comment by shuraa** [comment]
Ok, I think, that there is mapping problem. If I have change AuthorId mapping from:

```java
@Embeddable
public class AuthorId implements Serializable {

	private String id;

	public AuthorId(String id) {
		this.id = id;
	}
        
         ....
}
```
to
```java
@Embeddable
public class AuthorId implements Serializable {

	@Column(name = "_id")
	private String id;

	public AuthorId(String id) {
		this.id = id;
	}
        
         ....
}
```
test is passed.

**Pull request closed without merging**
