### PR TITLE
OGM-969 DefaultAssociationKeyMetada#equals

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-969

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@DavideD, did you spot an actual case where this is a problem? Or is it more a theoretical/aesthetic issue?

**Comment by DavideD** [comment]
> @DavideD, did you spot an actual case where this is a problem? Or is it more a theoretical/aesthetic issue?

You cannot use it as key in a Map (when you want to pre-compute some association specific operations, like Cypher queries).

**Comment by gunnarmorling** [comment]
Understood about the inability of using them in maps or sets, just wasn't sure where we'd actually be doing this :)

**Comment by gunnarmorling** [comment]
I think i'd rather add `columnName` to the hash code determination. Seems more in line with how we handle these things in general.

**Comment by DavideD** [comment]
> I think i'd rather add columnName to the hash code determination. Seems more in line with how we handle these things in general.

The two associations have the same column and table names, I'm not sure how adding the columns to the hashcode can solve the issue.

**Comment by gunnarmorling** [comment]
@DavideD The thing is that you need two distinct join tables for this mapping, one per association (In ORM you'd run into an exception with your original mapping).

And for the case we we use one table to map both navigations of a bi-di association (the bank account / account owner example), adding the column names should do the trick to make it distinguishable.

**Comment by gunnarmorling** [comment]
@DavideD, did you ever follow up on this one?

**Comment by DavideD** [comment]
> adding the column names should do the trick to make it distinguishable.

If you are talking about AssociationKeyMetadata#getColumnNames, that does not work.
Maybe I don't understand what you are suggesting, if you show me how you would change the equals I will test it on the Neo4j remote branch.

**Comment by Sanne** [comment]
so this is a requirement for #623 ? Is something preventing this to be merged first then?

**Comment by DavideD** [comment]
> so this is a requirement for #623 ? Is something preventing this to be merged first then?

The thing is that this mapping is not supported by ORM so I will close the pull request and change the tests.

**Pull request closed without merging**
