### PR TITLE
OGM-827 Setting the mongodb timeout for tests to 1000ms and refactori…

### PR DESCRIPTION
**Pull request by hferentschik**
…ng MongoDBDatastoreProvider#extractDatabase to remove retry logic and be generally simpler

### CODE REVIEW

**Comment by hferentschik** [comment]
@emmanuelbernard, is this what you had in mind?

**Comment by emmanuelbernard** [comment]
I've commented in the commit.

**Comment by hferentschik** [comment]
Where do we stand on this one now? I guess I can try to improve a bit on the error handling.

**Comment by emmanuelbernard** [comment]
The version in this PR - 9641063 - does not work as expected as we discussed.
So either:
1. we keep the original code minus the retry logic
2. you rewrite it but with the same semantic: we can think of changing the semantic in 5.0 if we manage find a better one

**Comment by hferentschik** [comment]
@emmanuelbernard, I pushed an update which just changes the timeout in hibernate.properties and just removes the retry logic. I have my doubts about the remaining {{if ( containsDatabase == null ) }} branch  and the whole logic in this method. See also https://hibernate.atlassian.net/browse/OGM-848.

Personally I would re-write the whole method.

**Comment by gunnarmorling** [comment]
> I am wondering how useful the hibernate.ogm.datastore.create_database option is for a production environment. 

Agreed, it mostly makes sense for testing purposes. Eventually, we plan to support the `hibernate.hbm2ddl.auto` option from ORM and remove `hibernate.ogm.datastore.create_database` in favor of that.

**Comment by gunnarmorling** [comment]
Merged; thanks, @hferentschik!

**Comment by hferentschik** [comment]
> Eventually, we plan to support the hibernate.hbm2ddl.auto option from ORM and remove hibernate.ogm.datastore.create_database in favor of that.

+1

**Pull request merged**
