### PR TITLE
OGM-1226 Update Neo4j and MongoDB dependencies

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-1226

@gsmet can you have a quick lookat this? After this I think I'm going to release OGM

### CODE REVIEW

**Comment by gsmet** [comment]
@DavideD there are test failures on Jenkins.

Btw, could you update the travis.yml file? Wondering if we should have a shell script which extracts the version from the pom.xml.

**Comment by DavideD** [comment]
> Btw, could you update the travis.yml file? Wondering if we should have a shell script which extracts the version from the pom.xml.

Yes, I guess we should

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
I triggered a new build.

There's something weird going on: http://ci.hibernate.org/job/hibernate-ogm-PR/1138/testReport/junit/org.hibernate.ogm.datastore.mongodb.test.index/MongoDBIndexTest/testSuccessfulTextIndexCreation/ .

**Comment by DavideD** [comment]
Fongo behaves differently.
I'm fixing it

**Comment by DavideD** [comment]
@gsmet  shoul be alright now

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request closed without merging**
