### PR TITLE
OGM-1523 Use WildFly 14 default Hibernate Search and ORM

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/OGM-1523

### CODE REVIEW

**Comment by fax4ever** [comment]
I have to fix the WildFly NoSql version

**Comment by fax4ever** [comment]
Hi @Sanne,
it's a very nice idea to parameterize the path of the module. So that we can restore the property. I'll do that.
It would be very nice having multiple WFs integration test, but I guess that in order to have this feature, we should provide different OGM feature pack module distributions. Shouldn't we?
Thanks for the insights!

**Comment by Sanne** [comment]
> It would be very nice having multiple WFs integration test, but I guess that in order to have this feature, we should provide different OGM feature pack module distributions. Shouldn't we?

I think you're right, to be truly able to test with ANY server version we would need more flexibility as possibly our modules structure would need to change internally.

That might be too much work, so not asking for that.  I just hope that merely having these properties in place we will be able to test some servers, specifically the ones which are similar enough to the current one (so with some luck the next WF15 betas could "just work" - no changes needed).

So let's just have the properties so that we can _test_ on different WildFly versions; we're not going to actually publish multiple module versions.

That will help to also know if - for example the modules pack we released for 14.0.1. is compatible with a slightly different server version (or not - it's just important to know about it).

Thanks

**Comment by fax4ever** [comment]
I put back the property. On the other hand, deepening better the issue, it would seem that the problem was the module slot and not the module name.

**Comment by DavideD** [comment]
This solution seems to work @fax4ever, is there anything else to update?

By the way, if these are properties, the creation of new job on Jenkins for the different WildFLy is very easy. We don't need to test each version of WildFly each time we run the build

**Comment by fax4ever** [comment]
@DavideD It's OK for me.

**Comment by fax4ever** [comment]
Thanks @DavideD!

**Pull request merged**
