### PR TITLE
OGM-961  refactor cassandra row handling

### PR DESCRIPTION
**Pull request by jhalliday**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jhalliday Could you rebase this to the latest master? I am having some trouble to apply it. Thanks!

**Comment by gunnarmorling** [comment]
Btw. the last two commits are not linked to your GitHub user (not using the email address given for your GH account).

**Comment by jhalliday** [comment]
/sigh. the 618 and 619 PRs merged out of order, hence breakage. I'll take a look.  The other thing is probably a git config file not surviving migration to my shiny new box.

**Comment by gunnarmorling** [comment]
@jhalliday I've taken the essential diff from your branch and created a new commit from scratch in your name. That way I could rebase it to master, as we usually avoid merge commits to keep the history linear.

**Pull request closed without merging**
