### PR TITLE
OGM-366 Neo4j remote integration (with a few fixes of gsmet)

### PR DESCRIPTION
**Pull request by gsmet**
This supersedes https://github.com/hibernate/hibernate-ogm/pull/687 .

Note: it's an upstream branch with name pr/687 so that Davide can write in it. I'll remove the branch once merged.

### CODE REVIEW

**Comment by DavideD** [comment]
OK, but what did you change?

**Comment by gsmet** [comment]
Just a few typos here and there in fact. Nothing fancy.

**Comment by gsmet** [comment]
Merged! Thanks Davide!

**Comment by DavideD** [comment]
Ah, OK...I thought you were waiting for a review :)

**Comment by DavideD** [comment]
Thanks

**Pull request closed without merging**
