### PR TITLE
OGM-401, OGM-640 Adding new supported types to type mapping lists per st...

### PR DESCRIPTION
**Pull request by gunnarmorling**
...ore

### CODE REVIEW

**Comment by DavideD** [comment]
Should we add in the documentation the float can have rounding issues?
At the moment I can see that 10.4 is stored as 10.399999618530273 in MongoDB

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-ogm/pull/472

**Comment by DavideD** [comment]
THanks

**Comment by gunnarmorling** [comment]
> Should we add in the documentation the float can have rounding issues?

I don't think that's needed here as it's a common issue with these types.

**Pull request merged**
