### PR TITLE
OGM-1247 Native distinct query with mongodb

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-1247

@raghav-jha I've squashed together your commits, cleaned them up and added some tests.

It looks great! Tomorrow I will check that your CLA is signed and then we can merge this.

Thanks

### CODE REVIEW

**Comment by raghav-jha** [comment]
@DavideD : When this will be merged ??

**Comment by DavideD** [comment]
Sombody needs to acknowledge the fact that you have signed the CLA.
I cannot check on my own and I'm waiting for him.

As soon as I have the confirmation I will include it.

Sorry for this complication, this process is not very good :(

**Comment by raghav-jha** [comment]
Oh ok. One more thing, after my PR is merged in the repo, then only OGM-1247 JIRA ticket will be assigned to me ??

**Comment by DavideD** [comment]
Can you create an account on JIRA?

**Comment by raghav-jha** [comment]
It's already created !!! using that only I have commented on the ticket earlier.

**Comment by DavideD** [comment]
Rebased and merged https://github.com/hibernate/hibernate-ogm/pull/829

Thanks [~raghav-jha]

**Pull request closed without merging**
