### PR TITLE
OGM-1436 Upgrade to ORM 5.2.16

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-1436

### CODE REVIEW

**Comment by gsmet** [comment]
@DavideD looks like there is a conflict. I suspect you haven't rebased your fork before making the change.

**Comment by DavideD** [comment]
Thanks @gsmet. my 5.3  branch wasn't up to date. Fixed now

**Comment by gsmet** [comment]
@DavideD +1 to merge once CI is green.

**Comment by Sanne** [comment]
merged! thank you all

**Pull request merged**
