### PR TITLE
OGM-1072 Update Neo4j to version 2.3.4

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-1072

A simle one before upgrading to 3

### CODE REVIEW

**Comment by Sanne** [comment]
merged

**Comment by Sanne** [comment]
@DavideD I see the JIRA issue is marking this for version 5.0.1 .
Does it need backporting, or did we not create a 5.0 maintenance branch yet?

**Comment by DavideD** [comment]
We haven't created a maintainance branch yet

**Comment by gunnarmorling** [comment]
For now I'd just merge to master. I don't think a 5.0.x branch is really needed at this point. Should we really wish to do a 5.0.1 (found a critical bug etc.) then we can discuss which issues to backport. So I'd also unset the 5.0.1 fix version from this issue until we really decided that it should go into 5.0.1.

**Comment by DavideD** [comment]
Sounds good to me, I've updated the fixVersion field

**Pull request merged**
