### PR TITLE
OGM-621 Reversing inheritance relationship of parent and BOM POM in orde...

### PR DESCRIPTION
**Pull request by gunnarmorling**
...r to avoid exposure of Guava and other test dependencies through the user-facing BOM

2nd try, basedon @Sanne's suggestion. I like it much better.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Jenkins, retest this, please.

**Comment by gunnarmorling** [comment]
Is this good to go?

**Comment by DavideD** [comment]
It is already included, I just forgot to close the pull.

I had to add a commit to move the distributionManagement tag in the BOM becuase there was an error when deploying the BOM

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-ogm/pull/471

**Pull request closed without merging**
