### PR TITLE
OGM-1030 Upgrading to Hibernate ORM 5.0.9

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by Sanne** [comment]
Is there a specific reason to upgrade?

Just wondering if we need special care to keep WF10 compatibility..

testing

**Comment by gunnarmorling** [comment]
Essentially I meant to go to the latest and greatest, but there is a test
failure. Need to investigate.

WF 10 has 5.0.7, so I was contemplating to align with that instead.

**Comment by Sanne** [comment]
Failed tests: 
      ListTest.testOrderedList:62->OgmTestCase.checkCleanCache:104 [Entity cache should be empty] expected:<[0]> but was:<[5]>
      ListTest.testOrderedListAndCompositeId:172->OgmTestCase.checkCleanCache:104 [Entity cache should be empty] expected:<[0]> but was:<[2]>
      ListTest.testRemovalOfElementFromOrderedListIsApplied:131 expected:<['L[eia]']> but was:<['L[uke]']>
      ListTest.testUpdateToElementOfOrderedListIsApplied:94 expected:<['L[isa]', 'Leia']> but was:<['L[uke]', 'Leia']>

Same test failure?

**Comment by gunnarmorling** [comment]
Yup.

**Comment by gunnarmorling** [comment]
That error shows up as of 5.0.7. Investigating.

**Comment by gunnarmorling** [comment]
Turns out that the update revealed one issue around updates to indexed element collections which used to be recreated prior to 5.0.7 and now not anymore: OGM-1034. Pushed one more commit for fixing that.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-ogm/pull/660

**Pull request closed without merging**
