### PR TITLE
OGM-571 Create-drop schema option

### PR DESCRIPTION
**Pull request by DavideD**
Follows: https://github.com/hibernate/hibernate-ogm/pull/903

So, it took me some time to wrap my head around this and in the process I've found that some things were inconsistent in our test suit This solution should work but I would like some feedback.

This PR changes the existing SchemaDefiner class, it removes the validateMapping method and add the equivalent methods for the schema generation. I did this because the validateMapping was alaways called with the initializeSchema and it is confusing to have the validateMapping and validateSchema in the same interface.

I also implemented the dropSchema for MongoDB althought I still need to find  a way to test it (I tested it manually right now).

### CODE REVIEW

**Comment by gsmet** [comment]
@DavideD any news on this one? I would have made the changes and merge but there is this question about sequences I would like an answer to.

Thanks!

**Comment by DavideD** [comment]
> @DavideD any news on this one? I would have made the changes and merge but there is this
> question about sequences I would like an answer to.

I somehow missed that comment, I'll have a look. I think it's something I forgot to update. I'll do that now

**Comment by gsmet** [comment]
@DavideD any news on this PR?

**Comment by gsmet** [comment]
@DavideD could we try to update this PR and close this subject? There are comments that should be addressed and a rebase is needed but IIRC we are very near mergeable state.

It's a nice improvement and it would be nice to have this in the next version of OGM.

**Comment by DavideD** [comment]
> @DavideD could we try to update this PR and close this subject? There are comments that should be addressed and a rebase is needed but IIRC we are very near mergeable state.
> 
> It's a nice improvement and it would be nice to have this in the next version of OGM.

Yes, I'm taking some time to review the other opened PRs and then I will go back to this one

**Comment by gsmet** [comment]
OK, cool, thanks!

**Comment by DavideD** [comment]
Closing this one and re-opening it when I finished with it

**Pull request closed without merging**
