### PR TITLE
OGM-1353 Use Infinispan cluster counters

### PR DESCRIPTION
**Pull request by DavideD**
Follows https://github.com/hibernate/hibernate-ogm/pull/930

https://hibernate.atlassian.net/browse/OGM-1353

Cluster counters are not supported for local caches, so we throw an exception when the users needs them but it is using local caches.

I've talked with the Infinispan team and they are going to implement it at some point: https://hibernate.atlassian.net/browse/OGM-1376

I needed to update some of the tests to make it work.

### CODE REVIEW

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Rebased to the latest changes

**Comment by DavideD** [comment]
@Sanne I'm going to integrate this and create a  new JIRA for the additional improvement we can do. Is that alright?

**Comment by DavideD** [comment]
I've created issue [OGM-1380](https://hibernate.atlassian.net/browse/OGM-1380)

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-ogm/pull/942

**Comment by Sanne** [comment]
Ok, yes. Was still running some stress tests but if I find any problem I'll open new issues :+1:

**Pull request merged**
