### PR TITLE
OGM-359 support stored procedures update

### PR DESCRIPTION
**Pull request by schernolyas**
The PR contains update of PR (https://github.com/hibernate/hibernate-ogm/pull/916)  to current state.

**Attention!** See org.hibernate.ogm.backendtck.storedprocedures.PositionalParametersStoredProcedureCallTest#testResultSetDynamicCallWithResultMapping

### CODE REVIEW

**Comment by DavideD** [comment]
[OGM-359](https://hibernate.atlassian.net/browse/OGM-359)

**Comment by schernolyas** [comment]
Closed. Reason is merge conflicts.
See new PR https://github.com/hibernate/hibernate-ogm/pull/976

**Comment by DavideD** [comment]
It seems you didn't rebase this but instead merged two branches?

**Comment by DavideD** [comment]
We don't merge branches on master, we rebase each PR so that we can have a clean history

**Pull request closed without merging**
