### PR TITLE
OGM-1351 Upgrade Libraries

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-1351
https://hibernate.atlassian.net/browse/OGM-1354
https://hibernate.atlassian.net/browse/OGM-1355
https://hibernate.atlassian.net/browse/OGM-1356

This patch will update Infinispan, Neo4j and MongoDB

### CODE REVIEW

**Comment by Sanne** [comment]
I don't like the name of this JIRA. If we have very generic "updating libraries" we'll end up having the same issue resolved in each and every release, sometimes the same in multiple branches, sometimes with adjustements needed for backporting conflict resolution, etc..

Please break them down in intelligible actions, e.g. "Update Infinispan Embedded to 9.1.3.Final"..

JIRA makes it quite easy to create a sequence of similar issues, use the checkbox at the bottom of the creation form.

**Comment by DavideD** [comment]
@Sanne Done

**Comment by gsmet** [comment]
@Sanne yeah, I created this issue so that we don't forget to upgrade all the libraries.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request closed without merging**
