### PR TITLE
OGM-1288 Constrain the edge direction when querying associations

### PR DESCRIPTION
**Pull request by hholierhoek**
Modifying BaseNeo4jEntityQueries.findAssociationPartialQuery to include
the edge direction between parent and owner.

### CODE REVIEW

**Comment by DavideD** [comment]
ok to test

**Comment by DavideD** [comment]
The patch looks good, I would like to add an additional test case though.

May I ask you how you tried to get the data from the datastore when you had the problem?

**Comment by hholierhoek** [comment]
Not sure this is what you're looking for, but the fetch was based on querying a secondary key, effectively in an @ElementCollection List<String>, which of course were stored in associated nodes. (In reality the list contained an object which is converted to string via @Converter(autoApply = true), but I suspect that doesn't matter.)

The parent/child relationship details are in the forum posting.

And we noticed the problem when a delete was done in the middle of a tree, and it removed the entire tree from its root.

If I missed your meaning let me know though.

**Comment by hholierhoek** [comment]
Still waiting for CLA approval it seems. I'll see if I can figure out where the email might have gone.

**Comment by hholierhoek** [comment]
Any chance you can find out from the inside what email address the CLA approval went to? I can't find the answer here. The FOSS and legal folks don't know. I've tried resending too.

**Comment by DavideD** [comment]
@hholierhoek Don't worry, I'll check and let you know

**Comment by DavideD** [comment]
@hholierhoek What name di you use to sign the CLA?

**Comment by hholierhoek** [comment]
Hubert Holierhoek
My login id on JBoss Developer is huberth.

**Comment by DavideD** [comment]
Did you select the Hibernate project when you signed the CLA? It seems we cannot find your user name in the queue. Could you eventually try to sign it again please? Just in case

**Comment by hholierhoek** [comment]
Most definitely it was Hibernate. See attachment.

cla

**Comment by hholierhoek** [comment]
Trying to sign it again gives the following error:

You already are a contributor, or have applied to be a contributor to Hibernate.

**Comment by Sanne** [comment]
hi @hholierhoek I'm sorry for the delay. I've raised a support ticket with the team running that service.

**Comment by hholierhoek** [comment]
Any update on the support ticket?

**Comment by hholierhoek** [comment]
I just noticed a reference to OGM-1290 in this thread, which I created and was working on a fix for... does it mess with this pull request if I've pushed that fix to my fork already?

**Comment by emmanuelbernard** [comment]
Hello @hholierhoek sorry for the long wait on this one. We had to track down where in the process your agreement got stuck. The system was expecting a click on the verification email you should have received. If you have not received it, can you click on the `Resend verification email` and check any spam filter you might have. Note if that's not your email address that was used, the appropriate person would have to check its mailbox.

Let me know how that goes.

**Comment by emmanuelbernard** [comment]
@hholierhoek about the reference to ` OGM-1290`, yes that's not the workflow we prefer.
What you should do is create a dedicated git branch (we call them topic branch) per issue you are working on (unless they are very closely related). That way you can push these branches to your GitHub repo and create dedicated pull requests for each.

For this time, we can deal with it. It would require Git kung fu on your side to fix it.

**Comment by hholierhoek** [comment]
I didn't receive a verification email. I just confirmed my email address is correct in my JBoss Developer account. And I've clicked the resend button close to half a dozen times. Nothing in my junk folder either.

But I presumed that email was going to someone with authority here. Is that not the case?

**Comment by emmanuelbernard** [comment]
OK let's make it a bit different. @hholierhoek, can you reply to this pull request by confirming that Nokia and you agreed to the Hibernate CLA? If you agree here, we will fix the technical hurdle later.

**Comment by hholierhoek** [comment]
Re: OGM-1290. Okay, thanks. Note that I do have another commit to come for that one before I can create a pull request.  Will I need to move this latest commit to another branch first?

**Comment by emmanuelbernard** [comment]
@hholierhoek if you know how to do that ( move this latest commit to another branch first), then go ahead and move all OGM-1290 in a dedicated branch. We will ignore the one that shows up here.

**Comment by hholierhoek** [comment]
Sure. I can confirm that I, and my manager (and his manager), at Nokia agree to the Hibernate CLA.

**Comment by hholierhoek** [comment]
I'll see what git 'kung fu' I can find to do that.

**Comment by hholierhoek** [comment]
Hmm... not sure I know what git-fu to do here. If I create a branch off my current master I don't know whether a pull request would pick up the first 1290 commit. If I branch it before 1288 I think we'll end up with merge conflicts - there are a reasonable number of overlapping lines changed.

Or maybe it's easier for you, too, if I just wait until this one is pulled, then commit to master and create a new pull request from my master? (And promise never to complicate things like this again!)

**Comment by DavideD** [comment]
@hholierhoek sorry for the late response, I'm not sure I understand the problem related to OGM-1290 if what you have works, send a PR so that I can have a look at it. Thanks a lot.

**Comment by hholierhoek** [comment]
Okay, there will be one more commit to my master (I've not pushed the latest one up), so the new pull request will contain a total of 3 commits - one for 1288 and two for 1290.

**Comment by hholierhoek** [comment]
I've done the last commit. It seems I can't create a new PR against the same fork/branch.

**Comment by DavideD** [comment]
Yes, there's no need to send a new pr I will pull your commit. By the way your previous  PR looks good but by working on a testcase before merging I've found some problems with some dialects. I'm working on it.

**Comment by DavideD** [comment]
I'm going to close this one and send a new PR for OGM-1290 that will include the commit you submitted.

The reason is that I need to add a test (I think) and fix checkstyle issues.

Check https://github.com/hibernate/hibernate-ogm/issues/863 for OGM-1288

**Pull request closed without merging**
