### PR TITLE
OGM-816 Using event context for implementing batching functionality

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@DavideD, @Sanne can we merge it?

**Comment by Sanne** [comment]
looking..

**Comment by DavideD** [comment]
Nice!

@gunnarmorling Looks good, I would just rename a method, I'll wait for your reply before merging it.

Could you also rebase it? There are a few minor conflicts.

Thanks

**Comment by gunnarmorling** [comment]
@DavideD, rebased and applied. Regarding the suggested renaming I am not not fully convinced. The "on..." prefix to me suggests an event handling method which doesn't really return anything. I have renamed it into `create()` and adapted the JavaDocs a bit. Would the new form work for you?

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-ogm/pull/529

Thanks

**Pull request merged**
