### PR TITLE
[TEST IGNORE] This is a test and I am pushing it

### PR DESCRIPTION
**Pull request by emmanuelbernard**
This is an example to see a student how this works.

### CODE REVIEW

**Comment by Sanne** [comment]
And this is were we give feedback!

Also, ci.hibernate.org will start testing this soon automatically.

**Comment by Sanne** [comment]
http://ci.hibernate.org/job/hibernate-ogm-PR/

**Comment by emmanuelbernard** [comment]
Oh boy, this CI server is realllllly slow ;)

**Comment by emmanuelbernard** [comment]
Closing PR as it's not good enough ;)

**Pull request closed without merging**
