### PR TITLE
OGM-1429 Support run java code for embedded mode

### PR DESCRIPTION
**Pull request by ntviet18**

### CODE REVIEW

**Comment by Sanne** [comment]
add to whitelist

**Comment by Sanne** [comment]
Hi @ntviet18 ! why did you close this? I didn't look at the details yet, but it looked very promising :+1:

**Comment by ntviet18** [comment]
Hi @Sanne, thank you. It's still in development process, so I decided to temporary close this.  I will reopen once it's ready.

**Comment by Sanne** [comment]
ok, great. If you need to talk with the team, feel free to join the development chat on HipChat.

Start here: https://hibernate.hipchat.com/chat then look for the "Hibernate OGM" room.

**Comment by ntviet18** [comment]
sure, thank you

**Comment by schernolyas** [comment]
Hi @Sanne !
Don't worry  .
It is draft version.  The code will go to hibernate ogm when it be ready for your review

**Pull request closed without merging**
