### PR TITLE
OGM-808 Removing maven-processor-plugin and do annottion provcessing …

### PR DESCRIPTION
**Pull request by hferentschik**
…via the maven-compiler plugin in order to have a better IDE integration

With this setup one can import the project into Intellij and rebuild the whole project directly w/o prior command line build. One can also modify the `Log` interfaces and just rebuild in the IDE making for a quick dev cycle.

### CODE REVIEW

**Comment by Sanne** [comment]
The good news is it works flawlessly in Eclipse too.

Unless I'm missing something about JMH, it seems this broke the performance testsuite though?
Or at least it needs new instructions in `org.hibernate.ogm.perftest.Launcher`

**Comment by gunnarmorling** [comment]
Merged. Good catch with the perf suite, @Sanne. I've added one more commit for updating the launcher instructions.

**Comment by hferentschik** [comment]
Awesome and good catch indeed :-)

**Comment by Sanne** [comment]
Thanks!

**Pull request merged**
