### PR TITLE
OGM-1513 Test element deletion in one-to-many bi-directional association

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/OGM-1513

Test for Won't Fix issue.

### CODE REVIEW

**Comment by DavideD** [comment]
Thanks, this looks good. Could you just rename the commit to something like:
`OGM-1513 Test element deletion in one-to-many bi-directional association `
and merge it, please?

**Comment by fax4ever** [comment]
Of course @DavideD. Thank you

**Comment by DavideD** [comment]
Rebased and Merged https://github.com/hibernate/hibernate-ogm/pull/1062

**Comment by fax4ever** [comment]
Thank you @DavideD !

**Pull request closed without merging**
