### PR TITLE
OGM-571 Honor "hbm2ddl" setting to initialize and drop the schema

### PR DESCRIPTION
**Pull request by ggaborg**

### CODE REVIEW

**Comment by DavideD** [comment]
> Hi, I have created a new pull request related to https://hibernate.atlassian.net/browse/OGM-571.
This is it #1111.
It does not solve the initial issue of lazy start of the mongodb datastore provider but maybe we can reach there after.

How come it doesn't solve the lazy initialization problem?

**Comment by ggaborg** [comment]
Because the start of the datastore provider has nothing to do with the creation of the schema. See MongoDBDatastoreProvider start method which extracts the database.

**Comment by ggaborg** [comment]
There is this test failing which is not failing on my side:
[INFO] Running org.hibernate.ogm.backendtck.jpa.JPAStandaloneORMAndOGMTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.273 s <<< FAILURE! - in org.hibernate.ogm.backendtck.jpa.JPAStandaloneORMAndOGMTest
[ERROR] testJTAStandaloneNoOgm(org.hibernate.ogm.backendtck.jpa.JPAStandaloneORMAndOGMTest)  Time elapsed: 0.267 s  <<< ERROR!
javax.persistence.PersistenceException: [PersistenceUnit: no-ogm] Unable to build Hibernate SessionFactory
	at org.hibernate.ogm.backendtck.jpa.JPAStandaloneORMAndOGMTest.testJTAStandaloneNoOgm(JPAStandaloneORMAndOGMTest.java:32)
Caused by: java.lang.UnsupportedOperationException: The application must supply JDBC connections
	at org.hibernate.ogm.backendtck.jpa.JPAStandaloneORMAndOGMTest.testJTAStandaloneNoOgm(JPAStandaloneORMAndOGMTest.java:32)

**Comment by DavideD** [comment]
Sorry, I can't remember. Why did you use branch 5.3 instead of master?

**Comment by ggaborg** [comment]
Because I'm working with wildfly 13 with hibernate-core 5.3.1.Final

**Comment by ggaborg** [comment]
Also, removing the create database property is breaking backward compatibility so this change should impose the changing of the minor version at least

**Pull request closed without merging**
