### PR TITLE
OGM-1152 WIP Dialect operation invocation tests started for the person taking OGM-1152

### PR DESCRIPTION
**Pull request by emmanuelbernard**
Not a compete test suite but has explanation for each operation being called.

### CODE REVIEW

**Comment by Sanne** [comment]
Could we merge this already, even if there's more work to do?

**Comment by gsmet** [comment]
@Sanne yes, I plan to finish this work soon. It needs some more love (typically, it doesn't take into account batching so it won't work with MongoDB dialect).

**Comment by emmanuelbernard** [comment]
@Sanne I'm pretty sure tests don't pass on all dialects as it is.

**Comment by gsmet** [comment]
I can confirm that :). Closing this one as I'm working on OGM-1152 and will provide another PR.

**Pull request closed without merging**
