### PR TITLE
OGM-1340 fix build of 'core' module for JDK9 (#14)

### PR DESCRIPTION
**Pull request by schernolyas**
The PR contains fix for task https://hibernate.atlassian.net/browse/OGM-1340

### CODE REVIEW

**Comment by Sanne** [comment]
The changes look good, but it doesn't seem to be enough; it's failing for me at

Hibernate OGM Aggregator ..

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project hibernate-ogm-parent: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce: java.lang.ExceptionInInitializerError: null

Did it work for you? which JVM did you use to test it?

I'm using

java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

**Comment by alaushkin** [comment]
Hi.
I'm using
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

Build success.

**Comment by schernolyas** [comment]
Hi @Sanne !

Yes. I need to update your JDK. I tried to execute "mvn clean install -DskipTests=true -Pjigsaw". It works fine.
But ... we will have problem with testing MongoDB:
java.lang.NoSuchMethodException: java.lang.Process.getPid()
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$1.getPid(Processes.java:195)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:98)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)

**Comment by Sanne** [comment]
nice! I merged this and added a for for OGM-1342, so now it works on JDK9
 - https://hibernate.atlassian.net/browse/OGM-1342

There's no need to skip testing.

**Pull request closed without merging**
