### PR TITLE
OGM-1246 Support for mapReduce native query added

### PR DESCRIPTION
**Pull request by raghav-jha**
- Moved Collation parsing from MongoDBQueryDescriptorBuilder.java to MongoDBDialect.java in order to reuse the same in mapReduce function.

- Done some refactoring in OscarWilde.java to add few more fields to the table in order to test mapReduce.

### CODE REVIEW

**Comment by Sanne** [comment]
@Hibernate-CI ok to test

**Comment by DavideD** [comment]
Thanks @raghav-jha, this contributions looks really good.

We have recently changed our approach about PR from contributors,
could you please rebase this PR to the latest master and confirm that you have read and accept the[ CONTRIBUTING.md](https://github.com/hibernate/hibernate-ogm/blob/master/CONTRIBUTING.md ) file and the [DCO](https://github.com/hibernate/hibernate-ogm/blob/master/dco.txt) one.

Thanks a lot and sorry it took me so long to review this.

**Comment by raghav-jha** [comment]
@DavideD: I have rebased this PR with the latest master.... I have read the Contributing.md and DCO file as well, but where do I confirm that?

**Comment by DavideD** [comment]
>  ... but where do I confirm that?

This message is good enough :)

**Comment by DavideD** [comment]
Thanks

**Comment by DavideD** [comment]
Rebased and merged https://github.com/hibernate/hibernate-ogm/pull/865

**Pull request closed without merging**
