### PR TITLE
Wrong javadoc

### PR DESCRIPTION
**Pull request by Sanne**
do I need to open 2 jira issues?

### CODE REVIEW

**Comment by gunnarmorling** [comment]
I'd so a single on.

Am 07.03.2017 12:43 nachm. schrieb "Sanne Grinovero" <
notifications@github.com>:

**Comment by DavideD** [comment]
> do I need to open 2 jira issues?

One would be enough for me

**Comment by Sanne** [comment]
> One would be enough for me

damn that's harder, these 2 changes are totally unrelated :)

**Comment by Sanne** [comment]
created JIRAs and merged

**Comment by DavideD** [comment]
Thanks @Sanne

**Pull request closed without merging**
