### PR TITLE
OGM-1084 Add script to run docker containers for OGM databases

### PR DESCRIPTION
**Pull request by emmanuelbernard**

### CODE REVIEW

**Comment by DavideD** [comment]
@emmanuelbernard Any particular reason to put his in the bin folder?

Under `bin` I have all the compiled classes form eclipse (I think). I would move it under `src/main/scripts` that's the place where we keep all our scripts

**Comment by gunnarmorling** [comment]
@DavideD, `bin` makes sense as it's a commonly used pattern for keeping executables and scripts. Still +1 for putting this script next to the other ones.

**Comment by DavideD** [comment]
Closing https://github.com/hibernate/hibernate-ogm/pull/696

I will move it and send a different PR

**Comment by emmanuelbernard** [comment]
Sorry, I'm from an era where scripts and other binaries were easily accessible in `bin` and not 3 level deep in a normalized structure ;)

**Pull request closed without merging**
