### PR TITLE
OGM-985 Upgrade MongoDB java Driver

### PR DESCRIPTION
**Pull request by twwwt**
Note that this PR includes commits 1a8b797 and 5403256 that relate to OGM-977. The commits that relate to OGM-985 are b8e101f and b04e165. However, at least the latter one (b04e165) directly depends on the former two (i.e., it can't be applied without the former two), so I didn't know how to better create the PR. Hope this doesn't create too much noise/confusion.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Add to whitelist.

**Comment by gunnarmorling** [comment]
@twwwt Could you rebase this to current master, please? And could you also change the author information of the commits so it links to your GitHub user (you seem to be using different email addresses). Thanks!

**Comment by gunnarmorling** [comment]
Ok, as I didn't hear back, I took the last two commits, squashed them into one and pushed that to master. Thanks for the update.

**Comment by vladmihalcea** [comment]
Hi @twwwt,

We are looking for someone to share their story about the Hibernate OGM in our newsletter. I think this is a good opportunity for your team to advertise your product too. Let me know if you are interested.

Thanks, Vlad

**Comment by twwwt** [comment]
Hi Vlad

Sounds interesting. We could write something on how we use OGM in one of our projects and what was the motivation to do so. Can you send me some details like deadline, amount of lines/words that you expect, and some links to previous articles in the newsletter.

Regards
Thorsten

**Comment by vladmihalcea** [comment]
Hi Thorsten,

I'm happy you want to share your story. Our newsletter is hosted on [in.relation.to](http://in.relation.to/). 
I was thinking of an interview article, similar to [this one](http://in.relation.to/2016/03/07/meet-martin-braun-youngest-hibernate-contributor/). It doesn't have to be too big, just to provide some answers to some of my questions.

There is no deadline, you can provide it whenever you can. You can send me an email to vlad at hibernate dot org, and I'll give you the list of questions that I have in mind. You can, of course, tweak them and provide other questions if you think they are better suited.

Vlad

**Comment by gunnarmorling** [comment]
Awesome, great to see this ball rolling!

**Pull request closed without merging**
