### PR TITLE
[PREVIEW] Migration to MongoDB Driver 3.x API

### PR DESCRIPTION
**Pull request by schernolyas**
Migration to MongoDB Driver 3.x API.

Need for perform task https://hibernate.atlassian.net/browse/OGM-786.

### CODE REVIEW

**Comment by DavideD** [comment]
@schernolyas DO you think it's ready to be merged or it is ust a preview? Github already tells me that there are conflicts so I'm wondering if there is something in particular I should check

**Comment by DavideD** [comment]
add to whitelist

**Comment by schernolyas** [comment]
Hi @DavideD !

It is NOT ready for merge. It ready for review only. I will fix conflicts during 1-2 days.

**Comment by DavideD** [comment]
If it cannot be merged, it is not ready for a review :)

What's the point of reviewing something that you know you have to change? Please, send a PR when you think it's ready to be merged

**Comment by schernolyas** [comment]
Okey @DavideD  ... no merge - no review :)

**Pull request closed without merging**
