### PR TITLE
OGM-868 Include git commit in the MANIFEST

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-868

It will add to the Manifest of the jars an entry called git-commit-id. Example:
```
Git-Commit-Id: f2b416ae402a9101f0fca8521bf4c3c86055cf96                                                   
 ```

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Looks good. Any particular motivation for introducing it?

**Comment by DavideD** [comment]
I don't have a particular scenario in mind, it just feels like it could  be handy to have this information
if some user has a problem with dependencies. 

That said, I added it mainly to see if it works (I was helping @Sanne ); It was easy to add and it might be nice to try it.

**Comment by DavideD** [comment]
Thinking about it,  this is helpful if someone uses SNAPSHOT to experiment with the features we add.
For example, it would be nmice for us to have this kind of information in the hibernate-orm project while we are experimenting with ORM5

**Comment by gunnarmorling** [comment]
Cool :)

**Pull request merged**
