### PR TITLE
OGM-1081 Rename classes and create  package for embedded in Neo4j

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/OGM-1081

Creates the following package for classes related to the embedde dialect: `org.hibernate.ogm.datastore.neo4j.embedded`

Use prefix EmbeddedNeo4j and BaseNeo4j for implementation classes

### CODE REVIEW

**Comment by gsmet** [comment]
You didn't rename Neo4jDialect to EmbeddedNeo4jDialect. Is it voluntarily?

**Comment by gsmet** [comment]
Typo in the name of EmbdddedNeo4jNodesTupleIterator .

**Comment by gsmet** [comment]
Looks like you missed RemoteTransactionCoordinatorBuilder .

**Comment by DavideD** [comment]
> You didn't rename Neo4jDialect to EmbeddedNeo4jDialect. Is it voluntarily?

I'm not sure we can rename it since it is an API

**Comment by gsmet** [comment]
Looks like you missed a few classes in:
- embedded.impl (especially the Neo4jDatastoreProvider)
- embedded.transaction.impl

**Comment by gsmet** [comment]
> I'm not sure we can rename it since it is an API

Yeah, maybe it's better to keep it that way for now and change it for a major version. Just wanted to be sure.

**Comment by DavideD** [comment]
> Looks like you missed a few classes in:

> embedded.impl (especially the Neo4jDatastoreProvider)
> embedded.transaction.impl

Weird, I'm sure I changed them. Probably something went wrong during the rebase. I'll fix this

**Comment by DavideD** [comment]
@gsmet Applied the changes and merged

Thanks

**Pull request merged**
