### PR TITLE
OGM-1065: Support Cassandra 3.0+

### PR DESCRIPTION
**Pull request by joexner**
Tests pass, including integration tests against Cassandra 3.7, 3.0 and 2.2

### CODE REVIEW

**Comment by gsmet** [comment]
add to whitelist

**Comment by Sanne** [comment]
@Hibernate-CI re test this please

**Comment by joexner** [comment]
@Hibernate-CI re test this please

**Comment by joexner** [comment]
The test runtime environment might be a little flaky, but the ModulesMagicDeckIT build fail has popped up twice in a row. Any idea what's up? I'll investigate in the meantime.

**Comment by gsmet** [comment]
Hi @joexner 

Thanks for taking a look into it. Much appreciated.

A couple of comments:
- is there a reason why you didn't target 3.0.2? Looks like it's the newest version
- I think the module issue is due to the fact that you didn't upgrade the Cassandra dependencies in the bom. The versions needs to be aligned with the ones from the Cassandra driver. So if we target 3.0.2, you need to set the codahaleMetricsVersion to 3.1.2. Guava version looks to be OK. You can test this locally by running `mvn clean verify`.

Btw, in the mean time, could you sign the CLA on https://cla.jboss.org/ for the *Hibernate* project? It's a one time thing for all your future contributions! Thanks!

Feel free to ping me if you have any further issue.

HTH

-- 
Guillaume

**Comment by joexner** [comment]
@Hibernate-CI re test this please

**Comment by gsmet** [comment]
@joexner I see you have fixed the issues.

Can you confirm me you signed the CLA?

Thanks!

**Comment by joexner** [comment]
Yup, I signed the CLA. :)

**Comment by gunnarmorling** [comment]
Are we sure that it still is going to work with C* 2.x? Wondering whether we should have CI job of sorts for ensuring that kind of thing. @gsmet, @DavideD, any thoughts?

**Comment by gsmet** [comment]
We didn't upgrade either CI or Travis, so yes, we are sure it works with 2.x. We are not sure it works with 3 though :).

**Comment by joexner** [comment]
The [docs](http://docs.datastax.com/en/developer/java-driver/3.0/java-driver/whatsNew2.html) say the new driver is backward-compatible with 2.2, and the integration tests pass locally against C* 2.2, 3.0 and 3.7.

**Comment by joexner** [comment]
re: CI database release compatibility testing, I've used [Arquillian Cube](https://github.com/arquillian/arquillian-cube) to test against different datastore and app server platforms/releases with some success.

**Comment by gsmet** [comment]
Yes, the issue is mostly to decide which versions we support and set up the CI for that on our part.

I stashed your changes and upgraded the Travis build to use Cassandra 3 (I changed your commit message to add the JIRA issue). Will create another JIRA for the CI stuff.

**Comment by gsmet** [comment]
Merged! Thanks!

**Pull request closed without merging**
